### PR TITLE
Blinds

### LINKED ISSUE #31: Blinds - Motor controls
Hi,

I don't seem to get my blinds (motor controls) in Home app. (Blinds are working fine through the Niko home app)
Hobby password is OK. The IP is also the correct one of the smarthub.

In the logging I don't see much:

[09/02/2021, 22:37:13] [NHC2] Initializing NHC2 platform...
[09/02/2021, 22:37:13] [NHC2] Suppressing accessories: 
[09/02/2021, 22:37:13] [NHC2] NHC2Platform finished initializing!
[09/02/2021, 22:37:13] [NHC2] NHC2Platform 'didFinishLaunching'

Is it because blinds are not supported yet in this plugin? If it should be, what can I do to check what my problem is?

Thanks in advance for any advice!

### PR DESCRIPTION
**Pull request by rubencallewaert**
Finished up support for all type of blinds offered by Niko.
(Direction is indeed an unsolvable issue, we should get in touch with Niko that they add a direction property on their events)
Most of the heavy lifting was already done by @christophevg thanks for that.

Apple homekit detects "moving" as a difference between target and current position.

closes #31 

Up to date with master and tested on my own devices.

Depends on my other 2 PR's in the nhc2-hobby-api repo:
https://github.com/homebridge-nhc2/nhc2-hobby-api/pull/17
https://github.com/homebridge-nhc2/nhc2-hobby-api/pull/18

### CODE REVIEW

**Comment by NielsCorneille** [comment]
Thank you, I have it working locally, would be nice to have it merged.

**Comment by NielsCorneille** [comment]
Thank you, I have it working locally, would be nice to have it merged.

**Comment by wttw** [comment]
Works nicely for me here, too.

It looks like the pull check build errored due to it using the version of nhc2-hobby-api that doesn't have the Moving attribute added.

**Comment by rubencallewaert** [comment]
Yes it does work the issue is that I can't publish a new version of nhc2-hobby-api to npm as the travis build isn't working:
https://github.com/homebridge-nhc2/nhc2-hobby-api/issues/26

Unfortunately the maintainer of these two projects does not seem to be active anymore.

I'm considering creating a fork so we can deploy new features again.

**Comment by rubencallewaert** [comment]
Hi Everyone,

I finally managed to port over both repositories to a new organisation.
The readme files might still be a bit out of date and I'll work on cleaning them up in the future.

You can find the new repository here.

https://github.com/openhomekit/homebridge-nhc2

@christophevg Since you were still active, if you are willing to contribute in the new org, contact me and I'll add you as a contributor.

Please try out the new package (v3.0.0), blinds support should be working there (as good as we can for now).

**Comment by christophevg** [comment]
Hi @rubencallewaert I'll start with installing/testing/... and we'll see from there.
Nice job, thanks, see you after the blip ;-)

**Pull request closed without merging**
